// Generated by CoffeeScript 1.10.0
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

SDP.GDT.Company = (function() {
  function Company(name, id) {
    var c;
    if (id == null) {
      id = name.replace(/\s/g, "");
    }
    this.toString = bind(this.toString, this);
    this.getPlatform = bind(this.getPlatform, this);
    c = Companies.getAllCompanies().find(function(val) {
      return val.id === id;
    });
    if (c == null) {
      c = Companies.createCompany({
        name: name,
        id: id
      });
    }
    this.platforms = c.platforms;
    this.addPlatform = c.addPlatform;
    this.addPlatform.bind(this);
    this.sort = c.sort;
    this.sort.bind(this);
    name = c.name;
    this.getName = function() {
      return name;
    };
    id = c.id;
    this.getId = function() {
      return id;
    };
  }

  Company.prototype.getPlatform = function(name) {
    var p;
    p = this.platforms.find(function(val) {
      return platform.name === name;
    });
    if (p == null) {
      p = this.platforms.find(function(val) {
        return platform.id === name;
      });
    }
    return p;
  };

  Company.prototype.toString = function() {
    return this.getName();
  };

  return Company;

})();
