// Generated by CoffeeScript 1.10.0
SDP.GDT.Date = (function() {
  var MAX_DATE, REQUIRED_VALS;

  REQUIRED_VALS = 3;

  function Date(year, month, week) {
    var val;
    this.year = year != null ? year : 1;
    this.month = month != null ? month : 1;
    this.week = week != null ? week : 1;
    if (typeof this.year === 'string') {
      val = this.year.split("/");
      while (val.length < REQUIRED_VALS) {
        val.push(1);
      }
      this.year = val[0];
      this.month = val[1];
      this.week = val[2];
    }
    if (typeof this.year === 'object' && typeof this.year.week === 'number' && typeof this.year.month === 'number' && typeof this.year.year === 'number') {
      this.week = this.year.week;
      this.month = this.year.month;
      this.year = this.year.year;
    }
    if (typeof this.year !== 'number') {
      this.year = 1;
    }
    if (typeof this.month !== 'number') {
      this.month = 1;
    }
    if (typeof this.week !== 'number') {
      this.week = 1;
    }
  }

  MAX_DATE = SDP.GDT.Date(260, 12, 4);

  Date.Max = function() {
    return Date(MAX_DATE);
  };

  Date.prototype.equals = function(date) {
    if (this === date) {
      return true;
    }
    if (!date) {
      return false;
    }
    return this.year === date.year && this.month === date.month && this.week === date.week;
  };

  Date.prototype.toString = function() {
    return "{0}/{1}/{2}".format(this.year, this.month, this.week);
  };

  return Date;

})();
