// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SDP.GDT.__notUniqueResearch = function(id) {
    var item;
    item = {
      id: id
    };
    return !Checks.checkUniqueness(item, 'id', Research.getAllItems());
  };

  SDP.GDT.Research = (function() {
    function Research(name, id) {
      if (id == null) {
        id = name;
      }
      this.toInput = bind(this.toInput, this);
      name = name.localize("research");
      this.getName = function() {
        return name;
      };
      this.canResearch = function(company) {
        return true;
      };
      this.v = void 0;
      this.category = SDP.Enum.ResearchCategory.ENGINE.value;
      this.categoryDisplayName = this.category.localize();
      this.pointsCost = 0;
      this.duration = 0;
      this.cost = 0;
      this.enginePoints = 0;
      this.engineCost = 0;
      this.group = void 0;
      this.canUse = function(game) {
        return true;
      };
      this.complete = function() {};
      this.consolePart = false;
      this.showXPGain = true;
      while (SDP.GDT.__notUniqueResearch(id)) {
        id += '_';
      }
      this.getId = function() {
        return id;
      };
    }

    Research.prototype.toInput = function() {
      return {
        id: this.getId(),
        name: this.getName(),
        canResearch: this.canResearch,
        canUse: this.canUse,
        v: this.v,
        pointsCost: this.pointsCost,
        duration: this.duration,
        cost: this.cost,
        enginePoints: this.enginePoints,
        engineCost: this.engineCost,
        category: this.category,
        categoryDisplayName: this.categoryDisplayName,
        group: this.group,
        complete: this.complete,
        consolePart: this.consolePart,
        showXPGain: this.showXPGain
      };
    };

    return Research;

  })();

}).call(this);
