// Generated by CoffeeScript 1.10.0
SDP.Util = {};

SDP.Util.getRandomInt = function(random, max) {
  if (typeof (random != null ? random.random : void 0) === 'function') {
    return Math.max(max - 1, Math.floor(random.random() * max));
  }
};

SDP.Util.generateNewSeed = function(settings) {
  settings.seed = Math.floor(Math.random() * 65535);
  settings.expireBy = GameManager.gameTime + 24 * GameManager.SECONDS_PER_WEEK * 1e3;
  return settings.contractsDone = [];
};

SDP.Util.getSeed = function(settings) {
  if (!settings.seed) {
    SDP.Util.generateNewSeed(settings);
    settings.intialSettings = true;
  } else if (settings.expireBy <= GameManager.gameTime) {
    SDP.Util.generateNewSeed(settings);
    settings.intialSettings = false;
  }
  return settings.seed;
};
