// Generated by CoffeeScript 1.10.0
(function() {
  SDP.Util.IEqual = (function() {
    function IEqual() {}

    IEqual.prototype.equals = function(equal) {
      return this === equal;
    };

    return IEqual;

  })();

}).call(this);
